title: "[Package Feedback]"
labels: ["Package Review"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the details about the package you're giving feedback on.
  - type: input
    id: package-name
    attributes:
      label: Package Name
      description: Enter the name of the package.
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - npm
        - pypi
        - crates
        - maven
    validations:
      required: true
  - type: input
    id: url-link
    attributes:
      label: URL Link
      description: Enter the package URL
    validations:
      required: true
  - type: input
    id: repo-activity-score
    attributes:
      label: Repository Activity Score
      description: Enter the Repository Score for the repository.
    validations:
      required: true
  - type: input
    id: author-activity-score
    attributes:
      label: Author Activity Score
      description: Enter the Author score
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: "Please provide any additional feedback or comments about the package."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for providing feedback on this package!
